const LOAD_ORDERS_AND_ACTIVITIES = 'LOAD_ORDERS_AND_ACTIVITIES';
const LOAD_ORDERS_AND_ACTIVITIES_SUCCESS = 'LOAD_ORDERS_AND_ACTIVITIES_SUCCESS';
const LOAD_ORDERS_AND_ACTIVITIES_FAIL = 'LOAD_ORDERS_AND_ACTIVITIES_FAIL';

export {
  LOAD_ORDERS_AND_ACTIVITIES,
  LOAD_ORDERS_AND_ACTIVITIES_SUCCESS,
  LOAD_ORDERS_AND_ACTIVITIES_FAIL,
};
